23.11 fb update queries for eIACUC2 Link
LabKey/onprcEHRModules pull request #1046
Opened 2024-06-10 18:00 UTC by jonesgaohsu

#### Rationale
Adding 2 queries to address Protocosl from eIACIC2

#### Related Pull Requests
* 

#### Changes
*

2024-06-13 15:55 UTC, brentlogan requested changes, later dismissed
Let's delete the eIACUCPopulateeIACUCfields file as it's not needed. I also edited/committed some capitalization issues in the xData.sql file.

2024-06-13 15:55 UTC, brentlogan commented on onprc_ehr/resources/queries/onprc_ehr/eIACUCPopulateeIACUCfields.sql
This file is unnecessary and can be deleted. This will also get rid of the XML error showing in the header.

2024-06-14 14:25 UTC, jonesgaohsu commented on onprc_ehr/resources/queries/onprc_ehr/eIACUCPopulateeIACUCfields.sql
THat makes sense and I will reove it from the Feature Branch

2024-06-14 14:25 UTC, jonesgaohsu reviewed
Cleanup looks good

2024-06-17 19:07 UTC, brentlogan approved these changes
@jonesgaohsu your changes look good. I'm going to request a review from you for my changes. Thanks!

2024-06-17 19:09 UTC, jonesgaohsu reviewed
All changes are as expected

2024-06-17 19:09 UTC, brentlogan reviewed
Approved.

2024-06-17 19:11 UTC, jonesgaohsu reviewed
All code as expected

2024-06-17 21:10 UTC, merged