23.11 fb e iacu cto prime end date
LabKey/onprcEHRModules pull request #1213
Opened 2024-12-20 17:01 UTC by jonesgaohsu

#### Rationale
RFevision of eIACUA End Date Process

#### Related Pull Requests
* 

#### Changes
*

2024-12-28 20:03 UTC, brentlogan requested changes
- eIACUCtoPrim**t**eProtocols.xml has a typo in its title.
- onprc_ehr-24.004-24.005.sql should not include the withdrawn protocol state in CTE ApprovedProtocols. We are interested in only those protocols that have ever been in the approved state. This code still works, though, as none of the withdrawn protocols has a non-NULL approval_date.

2024-12-30 18:20 UTC, kollil approved these changes

2025-01-03 00:43 UTC, brentlogan commented on onprc_ehr/resources/etls/eIACUCtoPrimteProtocols.xml
This file still has a typo in its name. Please correct this.

2025-01-09 19:37 UTC, jonesgaohsu commented
requested changes have been made, would like to deploy next week once review is completed

2025-01-14 18:44 UTC, brentlogan requested changes
In `onprc_ehr-24.004-24.005.sql`, please remove the test remarks in line 44, and clean up the formatting/indentation to be consistent across all three CTEs.

2025-01-14 21:00 UTC, jonesgaohsu commented
All changes have been made and awaiting final approval

2025-01-14 22:43 UTC, brentlogan approved these changes
Looks good!

2025-01-15 19:42 UTC, merged

2025-01-15 19:42 UTC, jonesgaohsu commented
Tested on UX Text and good results, Moving for deploy to Production tonight.