20.11 fb dcm weight validation error
LabKey/onprcEHRModules pull request #152
Opened 2021-05-06 16:27 UTC by jonesgaohsu

#### Rationale

#### Related Pull Requests
* 

#### Changes
*

2021-05-06 16:28 UTC, jonesgaohsu commented
Please review as this has been checked and is ready for Production

2021-05-06 17:16 UTC, labkey-jeckels requested changes
Did you intend to include all these changes? Or just the change to BCSScoreWeightsDemographicsProvider?

2021-05-06 17:16 UTC, labkey-jeckels commented on extscheduler/resources/schemas/dbscripts/sqlserver/extscheduler-21.410-21.411.sql
> +USE [Labkey_test]
Please remove the USE statement here. This will prevent it from working on production which uses a different DB name.

2021-05-06 17:16 UTC, labkey-jeckels commented on extscheduler/resources/schemas/dbscripts/sqlserver/extscheduler-21.410-21.411.sql
> +SET ANSI_NULLS ON
I recommend also removing these SET statements.

2021-05-06 17:16 UTC, labkey-jeckels commented on extscheduler/resources/schemas/extscheduler.xml
> +            <column columnName="DateDisbaled" />
Typo in "DateDisbaled"

2021-10-06 18:42 UTC, closed without merging

2021-10-06 18:42 UTC, jonesgaohsu commented
No Longer Neeeded