21.7 fb study details randal
LabKey/onprcEHRModules pull request #262
Opened 2021-10-13 16:57 UTC by jonesgaohsu

#### Rationale
<!This Feature Branch builds the dataset for Study Details for the Randal Database external schema and builds an etl to migrate the data from the external schema to the newly created onprc_ehr dataset  -->

#### Related Pull Requests
* 

#### Changes
*

2021-10-14 17:15 UTC, kollil approved these changes
Looks good

2021-10-14 17:18 UTC, labkey-jeckels requested changes

2021-10-14 17:18 UTC, labkey-jeckels commented on onprc_ehr/resources/schemas/dbscripts/sqlserver/onprc_ehr-21.201-21.202.sql
> +    )
This is a syntax error that's preventing the script from running successfully on TeamCity - you have two closing parentheses instead of one.

Also, many operations in LabKey (updates, deletes, etc) expect that there's a primary key defined on a table to identify the row that's being operated on. Is there one that can be added here?

2021-10-15 14:51 UTC, jonesgaohsu reviewed
THe changes requested have been completed please review and advise if other issues exist

2021-10-15 16:40 UTC, labkey-jeckels requested changes
The script is now running successfully on TeamCity, but the new table and its columns are missing from onprc_ehr.xml which is causing a different failure. Please update to include the new table.

2021-10-20 13:44 UTC, closed without merging