21.7 fb hansen queryto file xml
LabKey/onprcEHRModules pull request #270
Opened 2021-10-21 13:42 UTC by jonesgaohsu

#### Rationale
Per Request added the schema for StudyDetails_RandalData to onprc_ehr.xml

#### Related Pull Requests
* 

#### Changes
*

2021-10-21 13:43 UTC, jonesgaohsu commented
JOsh requested your review based on your request.  Thanks for keeping an eye on our code

2021-10-21 17:44 UTC, labkey-jeckels commented
@jonesgaohsu TeamCity is still reporting a mismatch - DPCO vs dpc0 (the letter O vs zero). Are you checking the test results that are linked from the pull request?

Additionally, the new queries are broken on TeamCity because it uses a different folder structure than PRIMe does. Instead of using "/ONPRC/EHR", please use "Site.{substitutePath moduleProperty('EHR','EHRStudyContainer')}" which will resolve the appropriate container path for the server on both TeamCity and PRIMe.

2021-10-21 17:48 UTC, jonesgaohsu commented
Thanks I will make the changes

2021-10-21 17:53 UTC, jonesgaohsu commented
Thanks and It appears I am not using the results correctly,  will step back and review the correct process and make sure I understand the process and results

2021-10-22 20:49 UTC, labkey-jeckels commented
@jonesgaohsu do you expect to work on this more today? The test failures are causing noise in other branches and repositories since they've been merged to the main 21.7 branch already, so I'd like to get them resolved ASAP.

2021-10-25 15:06 UTC, jonesgaohsu commented
completed update to correct left over " from query and verified thru dev instance

2021-10-25 18:10 UTC, labkey-jeckels requested changes

2021-10-25 18:10 UTC, labkey-jeckels commented on onprc_ehr/resources/etls/HansenQueriesToFile.xml
> +21.7_fb_HansenQuerytoFileXML
This looks like a copy/paste problem

2021-10-25 18:10 UTC, labkey-jeckels commented on onprc_ehr/resources/schemas/onprc_ehr.xml
> +            <column columnName="DPCO" />
This should be DPC0, not DPCO

```suggestion
            <column columnName="DPC0" />
```

2021-10-25 18:10 UTC, labkey-jeckels commented on onprc_ehr/resources/queries/onprc_ehr/RandData_Birth.sql
> +       d.cge,
This is causing a test failure. I assume it should be cage.

```suggestion
       d.cage,
```

2021-10-25 18:10 UTC, labkey-jeckels commented on onprc_ehr/resources/queries/onprc_ehr/RandData_Assignment.sql
> +        d.dType,
There is no dType column on the assignment dataset. Please correct or remove.

2021-10-25 18:10 UTC, labkey-jeckels commented on onprc_ehr/resources/queries/onprc_ehr/RandData_MHCData.sql
> + FROM  StudyDetails_RandalData s, Site.{substitutePath moduleProperty('EHR','EHRStudyContainer')}.study.mhcdata d
There is no mhcdata table or query in the study schema. Please remove or correct.

2021-10-25 18:10 UTC, labkey-jeckels commented on onprc_ehr/resources/queries/onprc_ehr/RandData_Flags.sql
> +       d.RequestedBy,
This column isn't part of the dataset definition that the test is loading so it's breaking. I'll add it and we can review the change in the Tuesday call.

2021-10-25 18:10 UTC, labkey-jeckels commented on onprc_ehr/resources/queries/onprc_ehr/RandData_AnimalGroups.sql
> +       d.isAssignedAtTime,
The test's definitions for the animal_group_members table doesn't include a project field, which means that ONPRC_EHRCustomizer isn't injecting the isAssignedAtTime and isAssignedToProtocolAtTime calculated fields. I'll add that field too.

2021-10-25 18:14 UTC, labkey-jeckels commented
Also, this pull request is currently targeting develop, not the 21.7 branch.

2021-10-27 16:27 UTC, jonesgaohsu commented on onprc_ehr/resources/queries/onprc_ehr/RandData_Assignment.sql
> +        d.dType,
CHanges have been made and successfully loaded

2021-10-27 16:29 UTC, jonesgaohsu commented on onprc_ehr/resources/schemas/onprc_ehr.xml
> +            <column columnName="DPCO" />
Changes made and successful passed auto testing

2021-10-27 16:30 UTC, jonesgaohsu commented on onprc_ehr/resources/queries/onprc_ehr/RandData_Assignment.sql
> +        d.dType,
This should have been assignment type and was reloaded this morning to correct the issue

2021-10-27 21:54 UTC, labkey-jeckels approved these changes
Let's go ahead and merge this. There are still two queries that are failing validation during the tests' study import (onprc_ehr.RandData_Flags and onprc_ehr.RandData_MHCData) but it's an improvement over the status quo. We'll need to do another followup FB to address them.

2021-10-28 19:28 UTC, jonesgaohsu commented
Merging to production instance, this is isoltated to the Hansen Lab

2021-10-28 19:28 UTC, merged