Update kinship and inbreeding coefficient tests
LabKey/onprcEHRModules pull request #575
Opened 2023-01-04 16:41 UTC by labkey-martyp

#### Rationale
Kinship calculations have been updated. Update the genetic tests here and add more thorough testing of kinship and inbreeding results.

#### Related Pull Requests
* https://github.com/LabKey/ehrModules/pull/493

#### Changes
* Add specific pedigree scenarios to the test data
* Verify kinship coefficients and inbreeding coefficents of those scenarios

2023-01-05 01:29 UTC, labkey-jeckels requested changes
The update test is failing on a duplicate row problem during the inserts.

2023-01-05 01:29 UTC, labkey-jeckels commented on onprc_ehr/test/src/org/labkey/test/tests/onprc_ehr/ONPRC_EHRTest.java
> +        assertEquals("Incorrect number of kinship rows before limiting animal selection", 48, kinshipTable.getDataRowCount()); // TODO: should be more
Is this TODO relevant?

2023-01-05 23:14 UTC, labkey-tchad reviewed
The test failure is because `createBirthRecords` no longer calls `deleteIfExists` before inserting birth records.
If you make `_hasCreatedBirthRecords` static, `createBirthRecords` should no-op for the second test to call it.
Alternatively, you could have `doSetup` create the birth records instead of making the individual tests do it. I can't imagine it takes terribly long, since its all done via API.

2023-01-10 20:48 UTC, labkey-jeckels approved these changes

2023-01-12 13:22 UTC, labkey-martyp commented on onprc_ehr/test/src/org/labkey/test/tests/onprc_ehr/ONPRC_EHRTest.java
> +        assertEquals("Incorrect number of kinship rows before limiting animal selection", 48, kinshipTable.getDataRowCount()); // TODO: should be more
Removed

2023-01-12 13:24 UTC, merged